WIP: Add new callback interface to receive the Capture creation event
DeployGate/deploygate-android-sdk pull request #96
Opened 2024-08-22 12:56 UTC by satsukies

2024-08-23 02:35 UTC, satsukies commented on sdk/src/test/java/com/deploygate/sdk/DeployGateSdkConfigurationInterfaceTest.java
> +        };
I forgot to initialize these variables.
ref. #95

2024-08-26 06:55 UTC, jmatsu requested changes
Please check the CI status.

2024-08-26 08:24 UTC, jmatsu approved these changes
LGTM

2024-08-26 08:44 UTC, satsukies commented
Thank you!

2024-08-26 08:44 UTC, merged